// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WeatherApi.Models;

namespace WeatherApi.Data
{
    public partial class WeatherdbContext : DbContext
    {
        public WeatherdbContext()
        {
        }

        public WeatherdbContext(DbContextOptions<WeatherdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=WeatherDB;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>(entity =>
            {
                entity.ToTable("City");

                entity.HasIndex(e => e.CityName, "ux_city")
                    .IsUnique();

                entity.Property(e => e.CityId).HasColumnName("city_id");

                entity.Property(e => e.CityName)
                    .HasMaxLength(32)
                    .IsUnicode(false)
                    .HasColumnName("cityName");
            });

            modelBuilder.Entity<Measurement>(entity =>
            {
                entity.HasKey(e => new { e.CityId, e.Timestamp })
                    .HasName("PK_Measurement_1");

                entity.ToTable("Measurement");

                entity.Property(e => e.CityId).HasColumnName("city_id");

                entity.Property(e => e.Timestamp)
                    .HasColumnType("datetime")
                    .HasColumnName("timestamp");

                entity.Property(e => e.IsArchived).HasColumnName("isArchived");

                entity.Property(e => e.Temperature).HasColumnName("temperature");

                entity.HasOne(d => d.City)
                    .WithMany(p => p.Measurements)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_Measurement_City");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}