// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeatherApi.Models
{
    public partial class Measurement
    {
        public int MeasurementId { get; set; }
        public string City { get; set; }
        public int Temperature { get; set; }
        public DateTime Timestamp { get; set; }
    }
}