// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeatherApi.Models
{
    public partial class Statistic
    {
        public int StatisticsId { get; set; }
        public int CityId { get; set; }
        public int LastMeasurementTemperature { get; set; }
        public DateTime LastMeasurementTime { get; set; }
        public double AvgTemperature { get; set; }
        public int MaxTemperature { get; set; }
        public int MinTemperature { get; set; }
        public DateTime FromTime { get; set; }
        public DateTime ToTime { get; set; }

        public virtual City City { get; set; }
    }
}